services:
  - type: web
    name: your-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html